name: Setup Public VPN

on:
  workflow_dispatch:

jobs:
  deploy-vpn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Setup IPSec VPN on VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$VPS_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $VPS_USER@$VPS_IP << 'EOF'
            # Install strongSwan for IPSec VPN
            sudo apt update && sudo apt install -y strongswan xl2tpd ppp iptables

            # Configure IP forwarding
            echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.conf
            sudo sysctl -p

            # Set up VPN credentials
            VPN_USER="publicvpn"
            VPN_PASSWORD="public123"
            VPN_PSK="vpnsharedkey"

            # Configure IPSec
            echo "config setup
            conn %default
                keyexchange=ikev2
                ike=aes256-sha2_256-modp2048!
                esp=aes256-sha2_256!
                dpdaction=clear
                dpddelay=300s
                rekey=no

            conn L2TP-PSK
                keyexchange=ikev1
                authby=secret
                ike=aes256-sha1-modp1024!
                esp=aes256-sha1!
                dpddelay=30
                dpdtimeout=120
                rekey=no
                left=%any
                leftid=$VPS_IP
                leftsubnet=0.0.0.0/0
                right=%any
                rightid=%any
                rightsubnet=0.0.0.0/0
                auto=add
            " | sudo tee /etc/ipsec.conf

            echo ": PSK \"$VPN_PSK\"" | sudo tee /etc/ipsec.secrets

            echo "$VPN_USER l2tpd \"$VPN_PASSWORD\" *" | sudo tee -a /etc/ppp/chap-secrets

            # Enable services
            sudo systemctl restart strongswan
            sudo systemctl enable strongswan

            # Output VPN Configuration
            echo "### VPN Connection Details ###"
            echo "Server: $VPS_IP"
            echo "Username: $VPN_USER"
            echo "Password: $VPN_PASSWORD"
            echo "Pre-Shared Key: $VPN_PSK"
            echo "VPN Type: L2TP/IPSec PSK"
          EOF
